version: '3.8'

services:
  analytics-service:
    build: .
    container_name: analytics-service
    ports:
      - "8084:8084"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3